export {default as  getAuth} from './getAuth'
export {default as  logIn} from './logIn'
export {default as  logOut} from './logOut'
export {default as signUp} from './signUp'
export {default as editInfo} from './editInfo'
